FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir fastapi uvicorn pydantic

COPY digifort_emulator.py .

EXPOSE 8080

CMD ["python", "digifort_emulator.py"]